Projekti-main/JobApplicationSystem/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using JobApplicationSystem.BAL.Services;
using JobApplicationSystem.DAL.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace JobApplicationSystem.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IApplicantService _applicantService;
        private readonly IJobService _jobService;
        private readonly IApplicationService _applicationService;

        public ApplicationController(IApplicantService applicantService, IJobService jobService, IApplicationService applicationService)
        {
            _applicantService = applicantService;
            _jobService = jobService;
            _applicationService = applicationService;
        }

        [Authorize(Roles = "Applicant")]
        public async Task<IActionResult> ApplyForJob(int jobId)
        {
            var job = await _jobService.GetJobByIdAsync(jobId);

            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicant = await _applicantService.GetApplicantDetailsAsync(loggedInUserId);

            var applicationModel = new Application
            {
                JobNavigation = job
            };

            if (_applicationService.CheckIfApplicantApplied(applicant.ApplicantId, jobId))
            {
                TempData["ErrorMessage"] = "You have already applied for this job.";
            }
            else if (job.LastDateToApply < DateTime.Now)
            {
                TempData["ErrorMessage"] = "The application deadline for this job has passed. You cannot apply.";
            }

            return View(applicationModel);
        }



        [Authorize(Roles = "Applicant")]
        [HttpPost]
        public async Task<IActionResult> ApplyForJob([Bind("ApplicationId,Education,Experience,Date,Applicant,Job,Resume")] Application application)
        {
            try
            {
                int? jobId = application.Job;
                application.Job = jobId;

                string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var applicant = await _applicantService.GetApplicantDetailsAsync(loggedInUserId);
                application.Applicant = applicant.ApplicantId;
                application.Education = applicant.Education;

                if (!_applicationService.CheckIfApplicantApplied(application.Applicant, application.Job))
                {
                    application.Date = DateTime.Now.ToString("yyyy-MM-dd"); 
                    await _applicationService.AddApplicationAsync(application);
                    return RedirectToAction("Applications", "Applicant");
                }
                else
                {
                    ViewData["ErrorMessage"] = "You have already applied for this job.";
                }
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(ex.ParamName, ex.Message);
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your application.");
            }

            return View(application);
        }

        public IActionResult UnauthorizedApplication()
        {
            return View();
        }

    }
}

Projekti-main/JobApplicationSystem/Controllers/JobController.cs
using JobApplicationSystem.BAL.Services;
using JobApplicationSystem.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace JobApplicationSystem.Controllers
{

    public class JobController : Controller
    {
        private readonly IJobService _jobService;
        private readonly IEmployerService _employerService;
        private readonly IApplicantService _applicantService;


        public JobController(IJobService jobService, IEmployerService employerService, IApplicantService applicantService)
        {
            _jobService = jobService;
            _employerService = employerService;
            _applicantService = applicantService;   
        }

        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> Index()
        {
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);

            if (employer != null)
            {
                var jobs = await _jobService.GetJobsByEmployerIdAsync(employer.EmployerId);
                return View(jobs);
            }
            else
            {
                return RedirectToAction("PersonalInfo", "Employer");
            }
        }

        [Authorize(Roles = "Employer, Applicant")]
        public async Task<ActionResult> Details(int id)
        {
            var job = await _jobService.GetJobByIdAsync(id);

            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        [Authorize(Roles = "Employer")]
        public ActionResult CreateJob()
        {
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!_employerService.HasProvidedPersonalInfo(loggedInUserId))
            {
                TempData["ErrorMessage"] = "You cannot take actions without providing personal information first.";
                return RedirectToAction("PersonalInfo", "Employer");
            }
            return View();
        }

        public ActionResult UnauthorizedJob()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateJob(Job job)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                    var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);
                    
                    if (employer != null)
                    {
                        job.Employer = employer.EmployerId;
                        job.Company = employer.Company;

                        await _jobService.AddJobAsync(job);

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }

                return View(job);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> EditJob(int id)
        {

            var job = await _jobService.GetJobByIdAsync(id);

            if (job == null)
            {
                return NotFound();
            }

            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);
            job.Company = employer.Company;


            if (job.Employer != employer.EmployerId)
            {
                return RedirectToAction(nameof(UnauthorizedJob));
            }

            return View(job);
        }

        [Authorize(Roles = "Employer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditJob(int id, Job updatedJob)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var job = await _jobService.GetJobByIdAsync(id);

                    if (job.Employer != updatedJob.Employer)
                    {
                        return RedirectToAction(nameof(UnauthorizedJob));
                    }

                    bool result = await _jobService.UpdateJobAsync(id, updatedJob);

                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return NotFound();
                    }
                }
                return View(updatedJob);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> DeleteJob(int id)
        {
            var job = await _jobService.GetJobByIdAsync(id);

            if (job == null)
            {
                return NotFound();
            }

            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);

            if (job.Employer != employer.EmployerId)
            {
                return RedirectToAction(nameof(UnauthorizedJob));
            }

            return View(job);
        }

        [Authorize(Roles = "Employer")]
        [HttpPost, ActionName("DeleteJob")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteJobConfirmed(int id)
        {
            var job = await _jobService.GetJobByIdAsync(id);
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);

            if (job.Employer != employer.EmployerId)
            {
                return RedirectToAction(nameof(UnauthorizedJob));
            }

            bool result = await _jobService.DeleteJobAsync(id);

            if (result)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }


        [Authorize(Roles = "Employer, Applicant")]
        public async Task<ActionResult> Jobs()
        {
            var allJobs = await _jobService.GetAllJobsAsync();
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            

            return View("Jobs", allJobs);
        }

        [Authorize(Roles = "Employer, Applicant")]
        public async Task<ActionResult> Search(string searchQuery)
        {
            var searchResults = await _jobService.SearchJobsAsync(searchQuery);
            var searchResultsList = searchResults.ToList();

            return View("Jobs", searchResultsList);
        }


    }
}

Projekti-main/JobApplicationSystem/Views/Job/CreateJob.cshtml
@model JobApplicationSystem.DAL.Models.Job


@{
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}
<div style="width: 80%; margin: 0 auto; background-color: #DBD6D2; padding: 20px; border-radius: 10px;font-family: 'Anek Gurmukhi', sans-serif;">
    <h3 class="text-center">Post a New Job</h3>
    <form asp-action="CreateJob">
        @Html.AntiForgeryToken()

        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-6 pt-3">
                <label asp-for="Title" style="font-weight: 600">Job Title</label>
                <input asp-for="Title" type="text" class="form-control" placeholder="Ex. Web Developer" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="col-md-6 pt-3">
                <label asp-for="NumberPosition" style="font-weight: 600">Number of Postition</label>
                <input asp-for="NumberPosition" type="number" class="form-control" placeholder="Enter number of position" />
                <span asp-validation-for="NumberPosition" class="text-danger"></span>
            </div>
        </div>
        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-12 pt-3">
                <label asp-for="Description" style="font-weight: 600">Description</label>
                <textarea asp-for="Description" class="form-control" placeholder="Enter Job Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-6 pt-3">
                <label asp-for="Education" style="font-weight: 600">Education Required</label>
                <input asp-for="Education" type="text" class="form-control" placeholder="Ex. BSc, MSc, PhD" />
                <span asp-validation-for="Education" class="text-danger"></span>
            </div>
            <div class="col-md-6 pt-3">
                <label asp-for="Experience" style="font-weight: 600">Experience Required</label>
                <input asp-for="Experience" type="text" class="form-control" placeholder="Ex. 2 years" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
        </div>
        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-6 pt-3">
                <label asp-for="Salary" style="font-weight: 600">Salary</label>
                <input asp-for="Salary" type="text" class="form-control" placeholder="Ex. 2500/Month" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="col-md-6 pt-3">
                <label asp-for="LastDateToApply" style="font-weight: 600">Last Date To Apply</label>
                <input asp-for="LastDateToApply" type="date" class="form-control"/>
                <span asp-validation-for="LastDateToApply" class="text-danger"></span>
            </div>
        </div>
        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-12 pt-3">
                <label asp-for="Address" style="font-weight: 600">Address</label>
                <textarea asp-for="Address" class="form-control" placeholder="Enter Work Location"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

        </div>
        <div class="row mr-lg-5 ml-lg-5 mb-3">
            
            <div class="col-md-6 pt-3">
                <label asp-for="CompanyLogo" style="font-weight: 600">Company Logo</label>
                <input asp-for="CompanyLogo" type="file" class="form-control" />
                <span asp-validation-for="CompanyLogo" class="text-danger"></span>
            </div>
        </div>
        <div class="row mr-lg-5 ml-lg-5">
            <div class="col-md-6 pt-3">
                <button type="submit" class="btn btn-primary">Post</button>
            </div>
        </div>
    </form>
</div>
<style>
    
    .btn-primary {
        background-color: #5A4D46; 
        border-color: #5A4D46;
        width: 100px;
        text-transform: uppercase;
        font-size: 20px;
        padding-top: 12px;
    }

        .btn-primary:hover {
            background-color: #483F38; 
            border-color: #483F38;
        }
</style>
<link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">

Projekti-main/JobApplicationSystem/Views/Job/DeleteJob.cshtml
@model JobApplicationSystem.DAL.Models.Job
@{
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}
<h2>Delete Job</h2>

<p>Are you sure you want to delete this job?</p>
<div>
    <h4>Job Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Title
        </dt>
        <dd class="col-sm-10">
            @Model.Title
        </dd>

        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>

        <dt class="col-sm-2">
            Education
        </dt>
        <dd class="col-sm-10">
            @Model.Education
        </dd>

        <dt class="col-sm-2">
            Experience
        </dt>
        <dd class="col-sm-10">
            @Model.Experience
        </dd>

        <dt class="col-sm-2">
            Number of Positions
        </dt>
        <dd class="col-sm-10">
            @Model.NumberPosition
        </dd>

        <dt class="col-sm-2">
            Last Date to Apply
        </dt>
        <dd class="col-sm-10">
            @Model.LastDateToApply?.ToShortDateString()
        </dd>

        <dt class="col-sm-2">
            Company
        </dt>
        <dd class="col-sm-10">
            @Model.Company
        </dd>

        <dt class="col-sm-2">
            Company Logo
        </dt>
        <dd class="col-sm-10">
            @Model.CompanyLogo
        </dd>

        <dt class="col-sm-2">
            Address
        </dt>
        <dd class="col-sm-10">
            @Model.Address
        </dd>

       
    </dl>

    <form asp-action="DeleteJob" asp-route-id="@Model.JobId" method="post">
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

Projekti-main/JobApplicationSystem/Views/Job/Details.cshtml
@model JobApplicationSystem.DAL.Models.Job

@{
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
    if (User.IsInRole("Applicant"))
    {
        Layout = "~/Views/Shared/_ApplicantLayout.cshtml";
    }
}

<style>
    .details-container {
        width: 70%;
        margin: 20px auto;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 10px;
        font-family: 'Anek Gurmukhi', sans-serif;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .logo-container {
        display: flex;
        align-items: center;
    }

        .logo-container img {
            width: 15%;
            margin-right: 20px;
        }

    .btn-primary {
        background-color: #5A4D46;
        border-color: #5A4D46;
        color: #fff;
    }

        .btn-primary:hover {
            background-color: #483F38;
            border-color: #483F38;
        }

    .btn-danger {
        background-color: #FF5A5F;
        border-color: #FF5A5F;
        color: #fff;
    }

        .btn-danger:hover {
            background-color: #E55658;
            border-color: #E55658;
        }
        div h5{
            font-weight: 600;
        }
</style>
<div class="details-container">
    <div class="logo-container">
        <img src="~/images/@Model.CompanyLogo" alt="Company Logo" class="img-fluid rounded-circle" />
        <h3>@Model.Company</h3>
    </div>

    <hr />
    <div>
        <h5>Job Title</h5>
        <p>@Model.Title</p>
    </div>
    <div>
        <h5>Description</h5>
        <p>@Model.Description</p>
    </div>

    <div>
        <h5>Education Required</h5>
        <p>@Model.Education</p>
    </div>

    <div>
        <h5>Experience Required</h5>
        <p>@Model.Experience</p>
    </div>

    <div>
        <h5>Number of Positions</h5>
        <p>@Model.NumberPosition</p>
    </div>

    <div>
        <h5>Last Date to Apply</h5>
        <p>@Model.LastDateToApply?.ToShortDateString()</p>
    </div>

    <div>
        <h5>Address</h5>
        <p>@Model.Address</p>
    </div>

    <div>
        <h5>Salary</h5>
        <p>@Model.Salary</p>
    </div>

    <div class="text-center mt-4">
        @if (User.IsInRole("Employer")){

            <a href="@Url.Action("EditJob", new { id = Model.JobId })" class="btn btn-primary">Edit</a>
            <a href="@Url.Action("DeleteJob", new { id = Model.JobId })" class="btn btn-danger ml-2">Delete</a>
            <a href="@Url.Action("Index")" class="btn btn-secondary ml-2">Go Back</a>
        }
        else
        {
            <a href="@Url.Action("ApplyForJob", "Application", new { jobId = Model.JobId })" class="btn btn-primary">Apply Now</a>
            <a href="@Url.Action("Jobs", "Job")" class="btn btn-secondary ml-2">Go Back</a>


        }
    </div>
</div>
<link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">

Projekti-main/JobApplicationSystem/Views/Job/EditJob.cshtml
@model JobApplicationSystem.DAL.Models.Job

@{
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}

<div style="width: 80%; margin: 0 auto; background-color: #DBD6D2; padding: 20px; border-radius: 10px; font-family: 'Anek Gurmukhi', sans-serif;">
    <h3 class="text-center">Edit Job</h3>
    <form asp-action="EditJob" asp-route-id="@Model.JobId" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="hidden" asp-for="Employer" />
        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-6 pt-3">
                <label asp-for="Title" style="font-weight: 600">Job Title</label>
                <input asp-for="Title" type="text" class="form-control" placeholder="Ex. Web Developer" />
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-6 pt-3">
                <label asp-for="NumberPosition" style="font-weight: 600">Number of Positions</label>
                <input asp-for="NumberPosition" type="number" class="form-control" placeholder="Enter number of positions" />
                @Html.ValidationMessageFor(model => model.NumberPosition, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-12 pt-3">
                <label asp-for="Description" style="font-weight: 600">Description</label>
                <input asp-for="Description" class="form-control" placeholder="Enter Job Description" />
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-6 pt-3">
                <label asp-for="Education" style="font-weight: 600">Education Required</label>
                <input asp-for="Education" type="text" class="form-control" placeholder="Ex. BSc, MSc, PhD" />
                @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-6 pt-3">
                <label asp-for="Experience" style="font-weight: 600">Experience Required</label>
                <input asp-for="Experience" type="text" class="form-control" placeholder="Ex. 2 years" />
                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-6 pt-3">
                <label asp-for="Salary" style="font-weight: 600">Salary</label>
                <input asp-for="Salary" type="text" class="form-control" placeholder="Ex. 2500/Month" />
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-6 pt-3">
                <label asp-for="LastDateToApply" style="font-weight: 600">Last Date To Apply</label>
                <input asp-for="LastDateToApply" type="date" class="form-control" />
                @Html.ValidationMessageFor(model => model.LastDateToApply, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row mr-lg-5 ml-lg-5 mb-3">
            <div class="col-md-12 pt-3">
                <label asp-for="Address" style="font-weight: 600">Address</label>
                <input asp-for="Address" class="form-control" placeholder="Enter Work Location" />
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row mr-lg-5 ml-lg-5 mb-3">
            
            <div class="col-md-6 pt-3">
                <div class="form-group">
                    <label asp-for="CompanyLogo" class="control-label">Current Company Logo: </label>
                    <img id="currentPhoto" src="~/images/@Model.CompanyLogo" alt="Current Photo" style="max-width: 100px; padding-bottom: 20px; padding-left: 10px;" />
                    <input type="file" id="fileInput" style="display: none" accept="image/*" />
                    <input type="hidden" asp-for="CompanyLogo" />
                    <button type="button" class="btn btn-outline-secondary" onclick="document.getElementById('fileInput').click()">Change Photo</button>
                    @Html.ValidationMessageFor(model => model.CompanyLogo, "", new { @class = "text-danger" })

                </div>
            </div>
        </div>

        <div class="row mr-lg-5 ml-lg-5">
            <div class="col-md-6 pt-3">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="@Url.Action("Index")" class="btn btn-secondary ml-2">Go Back</a>

            </div>
        </div>
    </form>
</div>

<style>
    .btn-primary {
        background-color: #5A4D46;
        border-color: #5A4D46;
        text-transform: uppercase;
    }

        .btn-primary:hover {
            background-color: #483F38;
            border-color: #483F38;
        }
</style>
<script>
    // Update the current photo and the hidden input field with the selected file's path
    document.getElementById('fileInput').addEventListener('change', function (e) {
        const fileInput = e.target;
        const fileName = fileInput.files[0].name;
        const currentPhoto = document.getElementById('currentPhoto');
        const photoUrlHidden = document.querySelector('input[type="hidden"][name="PhotoUrl"]');

        // Update the current photo's source to display the newly selected photo
        currentPhoto.src = URL.createObjectURL(fileInput.files[0]);

        // Set the value of the hidden input field to the file name
        photoUrlHidden.value = fileName;
    });
</script>
<link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">

Projekti-main/JobApplicationSystem/Views/Job/Jobs.cshtml
@model List<JobApplicationSystem.DAL.Models.Job>

@{

    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
    if (User.IsInRole("Applicant"))
    {
        Layout = "~/Views/Shared/_ApplicantLayout.cshtml";
    }
}

<style>
    * {
        font-family: 'Anek Gurmukhi', sans-serif;
    }

    .job-container {
        width: 100%;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin: 0 auto;
    }

    .job-card {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        transition: box-shadow 0.3s ease-in-out;
    }

        .job-card:hover {
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }

    .company-logo {
        width: 80px;
        height: 80px;
        object-fit: cover;
        border-radius: 50%;
        margin-bottom: 10px;
    }

    .company-info {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .company-name {
        font-weight: bold;
        margin-left: 10px;
    }

    .job-title {
        font-size: 18px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .job-description {
        margin-bottom: 10px;
    }

    .job-details {
        display: flex;
        justify-content: space-between;
        width: 100%;
    }

        .job-details span {
            color: #777;
        }

    .search-bar {
        margin-bottom: 20px;
    }

    .search-container {
        display: flex;
        position: relative;
    }

    #search {
        width: 100%;
        padding: 10px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    #search-btn {
        background-color: #5A4D46;
        border: none;
        color: #fff;
        cursor: pointer;
        padding: 10px;
        border-top-right-radius: 5px;
        border-bottom-right-radius: 5px;
        position: absolute;
        right: 0;
        display: flex;
        align-items: center;
        height: 45px;
        width:40px;
    }

        #search-btn:hover {
            background-color: #483F38;
        }

    .btn-primary {
        background-color: #5A4D46;
        border-color: #5A4D46;
    }

        .btn-primary:hover {
            background-color: #483F38;
            border-color: #483F38;
        }
</style>

<h1>All jobs posts</h1>
<hr />

<div class="search-bar">
    <form action="@Url.Action("Search", "Job")" method="get" class="search-container">
        <input type="text" id="search" name="searchQuery" placeholder="Search jobs by job title or company...">
        <button type="submit" id="search-btn">
            <i class="fa fa-search"></i>
        </button>
    </form>
</div>

@if (Model != null && Model.Count > 0)
{
    <div class="job-container row">
        @foreach (var job in Model)
        {
            <div class="col-md-4">
                <div class="job-card">
                    <div class="company-info">
                        <img src="~/images/@job.CompanyLogo" alt="Company Logo" class="company-logo" />
                        <div class="company-name" style="padding-left: 30px;">
                            <h4 style="font-weight: 900">@job.EmployerNavigation?.Company</h4>
                        </div>
                    </div>
                    <div class="job-title">@job.Title</div>
                    <div class="job-description">@job.Description</div>
                    <div class="job-details">
                        <span>@job.Salary</span>
                        <span>Last Date to Apply: @job.LastDateToApply?.ToShortDateString()</span>
                    </div>
                    @if (User.IsInRole("Applicant"))
                    {
                        <div class="btn-row" style="margin-left: 90px; margin-top: 20px;">
                            <a href="@Url.Action("ApplyForJob", "Application", new { jobId = job.JobId })" class="btn btn-primary">Apply</a>
                            <a href="@Url.Action("Details", "Job", new { id = job.JobId })" class="btn btn-secondary">View Details</a>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}
else
{
    <p>No jobs.</p>
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">

Projekti-main/JobApplicationSystem/Views/Job/UnauthorizedJob.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Unauthorized";
}
<header>
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-danger">You cannot take actions for jobs you haven't posted!</p>
</header>