Projekti-main/JobApplicationSystem/Controllers/FeedbackController.cs
using JobApplicationSystem.BAL.Services;
using JobApplicationSystem.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobApplicationSystem.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedbackService _feedbackService;

        public FeedbackController(IFeedbackService feedbackService)
        {
            _feedbackService = feedbackService;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var feedbackList = _feedbackService.GetAllFeedback();
            return View(feedbackList);
        }

        [Authorize(Roles = "Admin, Applicant, Employer")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Applicant, Employer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Feedback feedbackViewModel)
        {
            if (ModelState.IsValid)
            {
                var feedback = new Feedback
                {
                    Rating = feedbackViewModel.Rating,
                    Comments = feedbackViewModel.Comments,
                };

                _feedbackService.SubmitFeedback(feedback);

                return RedirectToAction("ThankYou");
            }

            return View(feedbackViewModel);
        }

        [Authorize(Roles = "Admin, Applicant, Employer")]
        public ActionResult ThankYou()
        {
            return View();
        }

    }
}

Projekti-main/JobApplicationSystem/Controllers/InterviewController.cs
using Microsoft.AspNetCore.Mvc;
using JobApplicationSystem.BAL.Services;
using JobApplicationSystem.DAL.Models;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

public class InterviewController : Controller
{
    private readonly IInterviewService _interviewService;
    private readonly IApplicationService _applicationService;
    private readonly IEmployerService _employerService;

    public InterviewController(IInterviewService interviewService, IApplicationService applicationService, IEmployerService employerService)
    {
        _interviewService = interviewService;
        _applicationService = applicationService;
        _employerService = employerService;
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Schedule(int applicationId)
    {
        var application = await _applicationService.GetApplicationByIdAsync(applicationId);

        if (application == null)
        {

            return RedirectToAction("UnauthorizedJob", "Job");
        }

        var interviewModel = new Interview
        {
            Application = applicationId,
            ApplicationNavigation = application,
        };

        return View(interviewModel);
    }


    [Authorize(Roles = "Employer")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Schedule(Interview interview)
    {
        if (ModelState.IsValid)
        {
            bool isConflict = await _interviewService.HasConflictAsync(interview);

            if (isConflict)
            {
                ModelState.AddModelError(string.Empty, "An interview already exists at the same time or the selected time is before today.");
                return View(interview);
            }

            await _interviewService.ScheduleInterviewAsync(interview);
            return RedirectToAction("EmployerScheduledInterviews");
        }

        return View(interview);
    }



    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Details(int id)
    {
        var interview = await _interviewService.GetInterviewByIdAsync(id);
        return View(interview);
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Edit(int id)
    {
        var interview = await _interviewService.GetInterviewByIdAsync(id);

        if (interview == null)
        {
            return NotFound();
        }

        return View(interview);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Edit(int id, Interview interview)
    {
        if (id != interview.InterviewId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            bool isConflict = await _interviewService.HasConflictAsync(interview);

            if (isConflict)
            {
                ModelState.AddModelError(string.Empty, "An interview already exists at the same time or the selected time is before today.");
                return View(interview);
            }


            var existingInterview = await _interviewService.GetInterviewByIdAsync(id);
            interview.Application = existingInterview.Application;

            await _interviewService.UpdateInterviewAsync(interview);

            return RedirectToAction("EmployerScheduledInterviews");
        }

        return View(interview);
    }


    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Delete(int id)
    {
        var interview = await _interviewService.GetInterviewByIdAsync(id);

        if (interview == null)
        {
            return NotFound();
        }

        return View(interview);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _interviewService.DeleteInterviewAsync(id);
        return RedirectToAction("EmployerScheduledInterviews");
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> EmployerScheduledInterviews()
    {
        string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);
        if (!_employerService.HasProvidedPersonalInfo(loggedInUserId))
        {
            TempData["ErrorMessage"] = "You cannot take actions without providing personal information first.";
            return RedirectToAction("PersonalInfo", "Employer");
        }
        var interviews = await _interviewService.GetScheduledInterviewsForEmployerAsync(employer.EmployerId);

        return View(interviews);
    }
}

Projekti-main/JobApplicationSystem/Controllers/JobController.cs
using JobApplicationSystem.BAL.Services;
using JobApplicationSystem.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace JobApplicationSystem.Controllers
{

    public class JobController : Controller
    {
        private readonly IJobService _jobService;
        private readonly IEmployerService _employerService;
        private readonly IApplicantService _applicantService;


        public JobController(IJobService jobService, IEmployerService employerService, IApplicantService applicantService)
        {
            _jobService = jobService;
            _employerService = employerService;
            _applicantService = applicantService;   
        }

        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> Index()
        {
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);

            if (employer != null)
            {
                var jobs = await _jobService.GetJobsByEmployerIdAsync(employer.EmployerId);
                return View(jobs);
            }
            else
            {
                return RedirectToAction("PersonalInfo", "Employer");
            }
        }

        [Authorize(Roles = "Employer, Applicant")]
        public async Task<ActionResult> Details(int id)
        {
            var job = await _jobService.GetJobByIdAsync(id);

            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        [Authorize(Roles = "Employer")]
        public ActionResult CreateJob()
        {
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!_employerService.HasProvidedPersonalInfo(loggedInUserId))
            {
                TempData["ErrorMessage"] = "You cannot take actions without providing personal information first.";
                return RedirectToAction("PersonalInfo", "Employer");
            }
            return View();
        }

        public ActionResult UnauthorizedJob()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateJob(Job job)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                    var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);
                    
                    if (employer != null)
                    {
                        job.Employer = employer.EmployerId;
                        job.Company = employer.Company;

                        await _jobService.AddJobAsync(job);

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }

                return View(job);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> EditJob(int id)
        {

            var job = await _jobService.GetJobByIdAsync(id);

            if (job == null)
            {
                return NotFound();
            }

            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);
            job.Company = employer.Company;


            if (job.Employer != employer.EmployerId)
            {
                return RedirectToAction(nameof(UnauthorizedJob));
            }

            return View(job);
        }

        [Authorize(Roles = "Employer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditJob(int id, Job updatedJob)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var job = await _jobService.GetJobByIdAsync(id);

                    if (job.Employer != updatedJob.Employer)
                    {
                        return RedirectToAction(nameof(UnauthorizedJob));
                    }

                    bool result = await _jobService.UpdateJobAsync(id, updatedJob);

                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return NotFound();
                    }
                }
                return View(updatedJob);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> DeleteJob(int id)
        {
            var job = await _jobService.GetJobByIdAsync(id);

            if (job == null)
            {
                return NotFound();
            }

            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);

            if (job.Employer != employer.EmployerId)
            {
                return RedirectToAction(nameof(UnauthorizedJob));
            }

            return View(job);
        }

        [Authorize(Roles = "Employer")]
        [HttpPost, ActionName("DeleteJob")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteJobConfirmed(int id)
        {
            var job = await _jobService.GetJobByIdAsync(id);
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var employer = await _employerService.GetEmployerDetailsAsync(loggedInUserId);

            if (job.Employer != employer.EmployerId)
            {
                return RedirectToAction(nameof(UnauthorizedJob));
            }

            bool result = await _jobService.DeleteJobAsync(id);

            if (result)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }


        [Authorize(Roles = "Employer, Applicant")]
        public async Task<ActionResult> Jobs()
        {
            var allJobs = await _jobService.GetAllJobsAsync();
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            

            return View("Jobs", allJobs);
        }

        [Authorize(Roles = "Employer, Applicant")]
        public async Task<ActionResult> Search(string searchQuery)
        {
            var searchResults = await _jobService.SearchJobsAsync(searchQuery);
            var searchResultsList = searchResults.ToList();

            return View("Jobs", searchResultsList);
        }


    }
}

Projekti-main/JobApplicationSystem/Views/Shared/_AdminLayout.cshtml
@using System.Security.Claims
@using Newtonsoft.Json

@{
    ViewData["Title"] = "Admin Dashboard";
    Layout = null;
    bool adminIdExists = ViewBag.AdminId != null && ViewBag.AdminId != 0;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - WorkLoop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="~/images/workloop-high-resolution-logo-transparent.png" type="image/x-icon">

    <link rel="stylesheet" href="~/JobApplicationSystem.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <style>
        #mySidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #4d331f;
            overflow-x: hidden;
            padding-top: 60px;
            transition: 0.5s;
        }

            #mySidenav a {
                padding: 28px 8px 8px 32px;
                text-decoration: none;
                font-size: 18px;
                color: #fff;
                display: block;
                transition: 0.3s;
                font-family: 'Roboto Condensed', sans-serif;
                font-weight: bold;
            }

            #mySidenav img {
                width: 32px;
                padding-right: 10px;
            }

            #mySidenav a:hover {
                color: #e5f3fd;
            }

            #mySidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding-left: 50px;
            margin-top: -15px;
            padding-right: 50px;
        }

            #main > h1 {
                font-family: 'Anek Gurmukhi', sans-serif;
                color: #4d331f;
                display: inline;
                margin-left: 10px;
            }

        #menu {
            width: 30px;
            cursor: pointer;
            margin-left: 10px;
            margin-top: 10px;
        }

        #logo {
            transition: transform 0.3s ease;
            width: 100px;
            margin-left: 40px;
        }

        ::-webkit-scrollbar {
            width: 4px;
        }

        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        ::-webkit-scrollbar-thumb {
            background: #888;        }

            ::-webkit-scrollbar-thumb:hover {
                background: #555;
            }

    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/workloop-high-resolution-logo-transparent.png" alt="" id="logo"></a>
               
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div id="mySidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

        <a asp-area="" asp-controller="Administrator" asp-action="Index"><img src="~/images/home.png" id="home">Home</a>
        @if (adminIdExists)
        {
            <a asp-area="" asp-controller="Administrator" asp-action="Details" asp-route-id="@Model.AdminId"><img src="~/images/profile.png">Profile</a>
        }
        else
        {
            <a asp-area="" asp-controller="Administrator" asp-action="PersonalInfo"><img src="~/images/profile.png">Profile</a>
        }
        <a asp-area="" asp-controller="Roles" asp-action="Index"><img src="~/images/roles.png">Roles</a>
        <a asp-area="" asp-controller="Feedback" asp-action="Index"><img src="~/images/feedback.png">View feedbacks</a>
    </div>
    <span onclick="openNav()"><img src="~/images/list.png" alt="" srcset="" id="menu"></span>
    <div id="main">
        @RenderBody()
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
            document.getElementById("logo").style.transform = "translateX(250px)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.getElementById("logo").style.transform = "translateX(0)";
        }
        
    </script>

    @RenderSection("Scripts", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</body>
</html>

Projekti-main/JobApplicationSystem/Views/Shared/_ApplicantLayout.cshtml
@using System.Security.Claims
@using Newtonsoft.Json

@{
    ViewData["Title"] = "Applicant Dashboard";
    Layout = null;
    bool applicantIdExists = ViewBag.ApplicantId != null && ViewBag.ApplicantId != 0;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - WorkLoop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="~/images/workloop-high-resolution-logo-transparent.png" type="image/x-icon">

    <link rel="stylesheet" href="~/JobApplicationSystem.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <style>
        #mySidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #4d331f;
            overflow-x: hidden;
            padding-top: 60px;
            transition: 0.5s;
        }

            #mySidenav a {
                padding: 28px 8px 8px 32px;
                text-decoration: none;
                font-size: 18px;
                color: #fff;
                display: block;
                transition: 0.3s;
                font-family: 'Roboto Condensed', sans-serif;
                font-weight: bold;
            }

            #mySidenav img {
                width: 32px;
                padding-right: 10px;
            }

            #mySidenav a:hover {
                color: #e5f3fd;
            }

            #mySidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding-left: 50px;
            margin-top: -15px;
            padding-right: 50px;
        }

            #main > h1 {
                font-family: 'Anek Gurmukhi', sans-serif;
                color: #4d331f;
                display: inline;
                margin-left: 10px;
            }

        #menu {
            width: 30px;
            cursor: pointer;
            margin-left: 10px;
            margin-top: 10px;
        }

        #logo {
            transition: transform 0.3s ease;
            width: 100px;
            margin-left: 40px;
        }

        ::-webkit-scrollbar {
            width: 4px;
        }

        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        ::-webkit-scrollbar-thumb {
            background: #888;
        }

            ::-webkit-scrollbar-thumb:hover {
                background: #555;
            }

    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/workloop-high-resolution-logo-transparent.png" alt="" id="logo"></a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div id="mySidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

        <a asp-area="" asp-controller="Applicant" asp-action="Index"><img src="~/images/home.png" id="home">Home</a>
        @if (applicantIdExists)
        {
            <a asp-area="" asp-controller="Applicant" asp-action="Details"><img src="~/images/profile.png">Profile</a>
        }
        else
        {
            <a asp-area="" asp-controller="Applicant" asp-action="PersonalInfo"><img src="~/images/profile.png">Profile</a>
        }
        <a asp-area="" asp-controller="Job" asp-action="Jobs"><img src="~/images/suitcase.png">Job Posts</a>
        <a asp-area="" asp-controller="Applicant" asp-action="Applications"><img src="~/images/form.png">Your applications and Interviews</a>
        <a asp-area="" asp-controller="Feedback" asp-action="Create"><img src="~/images/feedback.png">Give feedback</a>

    </div>
    <span onclick="openNav()"><img src="~/images/list.png" alt="" srcset="" id="menu"></span>
    <div id="main">
        @RenderBody()
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
            document.getElementById("logo").style.transform = "translateX(250px)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.getElementById("logo").style.transform = "translateX(0)";
        }

    </script>

    @RenderSection("Scripts", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</body>
</html>

Projekti-main/JobApplicationSystem/Views/Shared/_EmployerLayout.cshtml
@using System.Security.Claims
@using Newtonsoft.Json

@{
    ViewData["Title"] = "Employer Dashboard";
    Layout = null;
    bool employerIdExists = ViewBag.EmployerId != null && ViewBag.EmployerId != 0;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - WorkLoop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="~/images/workloop-high-resolution-logo-transparent.png" type="image/x-icon">

    <link rel="stylesheet" href="~/JobApplicationSystem.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anek+Gurmukhi&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <style>
        #mySidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #4d331f;
            overflow-x: hidden;
            padding-top: 60px;
            transition: 0.5s;
        }

            #mySidenav a {
                padding: 28px 8px 8px 32px;
                text-decoration: none;
                font-size: 18px;
                color: #fff;
                display: block;
                transition: 0.3s;
                font-family: 'Roboto Condensed', sans-serif;
                font-weight: bold;
            }

            #mySidenav img {
                width: 32px;
                padding-right: 15px;
            }

            #mySidenav a:hover {
                color: #e5f3fd;
            }

            #mySidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding-left: 50px;
            margin-top: -15px;
            padding-right: 50px;
        }

            #main > h1 {
                font-family: 'Anek Gurmukhi', sans-serif;
                color: #4d331f;
                display: inline;
                margin-left: 10px;
            }

        #menu {
            width: 30px;
            cursor: pointer;
            margin-left: 10px;
            margin-top: 10px;
        }

        #logo {
            transition: transform 0.3s ease;
            width: 100px;
            margin-left: 40px;
        }

        ::-webkit-scrollbar {
            width: 4px;
        }

        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        ::-webkit-scrollbar-thumb {
            background: #888;
        }

            ::-webkit-scrollbar-thumb:hover {
                background: #555;
            }

    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/workloop-high-resolution-logo-transparent.png" alt="" id="logo"></a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div id="mySidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>


        <a asp-area="" asp-controller="Employer" asp-action="Index"><img src="~/images/home.png" id="home">Home</a>
        @if (employerIdExists)
        {
            <a asp-area="" asp-controller="Employer" asp-action="Details"><img src="~/images/profile.png">Profile</a>
        }
        else
        {
            <a asp-area="" asp-controller="Employer" asp-action="PersonalInfo"><img src="~/images/profile.png">Profile</a>
        }

        <a asp-area="" asp-controller="Job" asp-action="CreateJob"><img src="~/images/briefcase.png">Post a Job</a>
        <a asp-area="" asp-controller="Job" asp-action="Index"><img src="~/images/list (1).png">My Job Posts</a>
        <a asp-area="" asp-controller="Job" asp-action="Jobs"><img src="~/images/suitcase.png">All Job Posts</a>
        <a asp-area="" asp-controller="Interview" asp-action="EmployerScheduledInterviews"><img src="~/images/job-interview.png">Scheduled interviews</a>
        <a asp-area="" asp-controller="Feedback" asp-action="Create"><img src="~/images/feedback.png">Give feedback</a>


    </div>
    <span onclick="openNav()"><img src="~/images/list.png" alt="" srcset="" id="menu"></span>
    <div id="main">
        @RenderBody()
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
            document.getElementById("logo").style.transform = "translateX(250px)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.getElementById("logo").style.transform = "translateX(0)";
        }

    </script>

    @RenderSection("Scripts", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</body>
</html>